import { db } from '@/db';
import { satellites } from '@/db/schema';

async function main() {
    const sampleSatellites = [
        {
            name: 'GSAT-30',
            type: 'Communication',
            status: 'Active',
            lat: 28.6139,
            lon: 77.2090,
            alt: 35786,
            userId: 'demo-user-1',
            launchDate: new Date('2024-01-15').toISOString(),
            description: 'Communication satellite for broadband connectivity across India',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'IRNSS-1I',
            type: 'Communication',
            status: 'Active',
            lat: 19.0760,
            lon: 72.8777,
            alt: 35786,
            userId: 'demo-user-1',
            launchDate: new Date('2024-02-20').toISOString(),
            description: 'NavIC navigation satellite for positioning services',
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'RISAT-2C',
            type: 'Earth Obs',
            status: 'Active',
            lat: 12.9716,
            lon: 77.5946,
            alt: 555,
            userId: 'demo-user-1',
            launchDate: new Date('2024-03-10').toISOString(),
            description: 'Radar imaging satellite for all-weather surveillance',
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            name: 'Cartosat-3B',
            type: 'Earth Obs',
            status: 'Active',
            lat: 22.5726,
            lon: 88.3639,
            alt: 505,
            userId: 'demo-user-1',
            launchDate: new Date('2024-04-25').toISOString(),
            description: 'High-resolution Earth observation for cartography',
            createdAt: new Date('2024-04-25').toISOString(),
            updatedAt: new Date('2024-04-25').toISOString(),
        },
        {
            name: 'INSAT-3DR',
            type: 'Weather',
            status: 'Active',
            lat: 17.3850,
            lon: 78.4867,
            alt: 35786,
            userId: 'demo-user-1',
            launchDate: new Date('2023-12-12').toISOString(),
            description: 'Weather monitoring and disaster warning system',
            createdAt: new Date('2023-12-12').toISOString(),
            updatedAt: new Date('2023-12-12').toISOString(),
        },
        {
            name: 'OCEANSAT-4',
            type: 'Earth Obs',
            status: 'Active',
            lat: 13.0827,
            lon: 80.2707,
            alt: 720,
            userId: 'demo-user-1',
            launchDate: new Date('2024-05-08').toISOString(),
            description: 'Ocean observation for fishing and climate studies',
            createdAt: new Date('2024-05-08').toISOString(),
            updatedAt: new Date('2024-05-08').toISOString(),
        },
        {
            name: 'EOS-07',
            type: 'Earth Obs',
            status: 'Active',
            lat: 23.0225,
            lon: 72.5714,
            alt: 670,
            userId: 'demo-user-1',
            launchDate: new Date('2024-06-18').toISOString(),
            description: 'Electro-optical satellite for land resource monitoring',
            createdAt: new Date('2024-06-18').toISOString(),
            updatedAt: new Date('2024-06-18').toISOString(),
        },
        {
            name: 'GSAT-24',
            type: 'Communication',
            status: 'Active',
            lat: 26.9124,
            lon: 75.7873,
            alt: 35786,
            userId: 'demo-user-1',
            launchDate: new Date('2024-07-22').toISOString(),
            description: 'Communication satellite for DTH and broadband services',
            createdAt: new Date('2024-07-22').toISOString(),
            updatedAt: new Date('2024-07-22').toISOString(),
        },
        {
            name: 'EMISAT-2',
            type: 'Remote Sensing',
            status: 'Testing',
            lat: 18.5204,
            lon: 73.8567,
            alt: 750,
            userId: 'demo-user-1',
            launchDate: new Date('2024-08-30').toISOString(),
            description: 'Electronic intelligence satellite for surveillance',
            createdAt: new Date('2024-08-30').toISOString(),
            updatedAt: new Date('2024-08-30').toISOString(),
        },
        {
            name: 'Aditya-L2',
            type: 'Remote Sensing',
            status: 'Testing',
            lat: 26.8467,
            lon: 80.9462,
            alt: 1500000,
            userId: 'demo-user-1',
            launchDate: new Date('2024-09-15').toISOString(),
            description: 'Solar observation satellite from L1 Lagrange point',
            createdAt: new Date('2024-09-15').toISOString(),
            updatedAt: new Date('2024-09-15').toISOString(),
        }
    ];

    await db.insert(satellites).values(sampleSatellites);
    
    console.log('✅ Satellites seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});